name: yemenwe
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  #bubble_bottom_bar: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  get: ^3.2.2
  flutter_phoenix:
  #cached_network_image: ^2.2.0+1
  fluttertoast: ^6.0.1
  line_icons: ^0.2.0
  #flip_card: ^0.4.4
  #youtube_player_flutter: ^7.0.0+7
  flutter_staggered_animations: "^0.1.2"
  share: ^0.6.4+3
  url_launcher: ^5.5.0
  awesome_dialog: ^1.1.3
  #readmore: ^1.0.0
  frino_icons: ^1.0.1
  #audioplayers: ^0.15.1
  dio:
  #dio_http_cache:
  provider: ^4.3.2+1
  shared_preferences: ^0.5.10
  #flutter_plugin_pdf_viewer: ^1.0.7
  percent_indicator:
  #path_provider:
  #permission_handler:
  flutter_windowmanager:   #************************
  #like_button:
  smooth_star_rating:
  shimmer:
  cached_network_image:
  connectivity:
  webview_flutter:
  #flutter_progress_dialog:
  custom_dialog:
  progress_dialog:
  flutter_swiper:
  #persistent_bottom_nav_bar:
  #simple_url_preview:
  #flutter_link_preview:
  flutter_html: "0.11.1"
  eva_icons_flutter:
  ionicons:
  quick_feedback:
  ff_navigation_bar:
  flutter_native_splash:
  getwidget:




dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_native_splash:
flutter_native_splash:
  image: images/newlogo.png
  color: "ffffff"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ArabicFont
      fonts:
        - asset: fonts/arabicfont.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: ArbFONTS-Droid
      fonts:
        - asset: fonts/ArbFONTS-Droid-Arabic-Kufi.ttf
        - asset: fonts/ArbFONTS-DroidKufi-Bold.ttf
        - asset: fonts/ArbFONTS-DroidKufi-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
